plugins {
	id('idea')
	id('maven-publish')
	id('com.modrinth.minotaur') version '2.+'
	id('com.matthewprenger.cursegradle') version '1.4.0'
	id 'org.jetbrains.gradle.plugin.idea-ext' version '1.3'
	id 'net.neoforged.moddev.legacyforge' version '2.0.80'
}

group = "thedarkcolour.gendustry"
version = gendustryVersion
base.archivesName = "gendustry-$minecraftVersion"

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

legacyForge {
	version = "1.20.1-$forgeVersion"

	//accessTransformers = files('src/main/resources/META-INF/accesstransformer.cfg')
	// Set to false because Forge has broken access transformers
	//validateAccessTransformers = true

	// Add Parchment parameter mappings
	parchment {
		mappingsVersion = project.mappingsVersion
		minecraftVersion = project.minecraftVersion
	}

	runs {
		configureEach {
			logLevel = org.slf4j.event.Level.DEBUG
			jvmArgument '-XX:+AllowEnhancedClassRedefinition'
			jvmArgument '-XX:+IgnoreUnrecognizedVMOptions'
		}

		client {
			client()
		}

		server {
			server()
			gameDirectory.set(project.layout.projectDirectory.dir('run/server'))
			programArgument '--nogui'
		}

		data {
			data()
			programArguments.addAll('--mod', 'gendustry', '--all', '--output', file('src/generated/resources/').absolutePath, '--existing', file('src/main/resources/').absolutePath)
		}
	}

	mods {
		gendustry {
			sourceSet sourceSets.main
		}
	}
}

repositories {
	maven {
		name = 'jei'
		url = 'https://maven.blamejared.com/'
		content { includeGroup "mezz.jei" }
	}
	maven {
		name = "Patchouli"
		url = "https://maven.blamejared.com/"
	}
	maven {
		url "https://cursemaven.com"
		content {
			includeGroup "curse.maven"
		}
	}
	maven {
		name = 'ModKit'
		url 'https://jitpack.io'
		content { includeGroup 'com.github.thedarkcolour' }
	}
	exclusiveContent {
		forRepository {
			maven {
				name = "Modrinth"
				url = "https://api.modrinth.com/maven"
			}
		}
		filter {
			includeGroup "maven.modrinth"
		}
	}
}

dependencies {
	// JEI OPTIONAL
	modCompileOnly "mezz.jei:jei-$minecraftVersion-common-api:$jeiVersion"
	modCompileOnly "mezz.jei:jei-$minecraftVersion-forge-api:$jeiVersion"
	modRuntimeOnly "mezz.jei:jei-$minecraftVersion-forge:$jeiVersion"
	// PATCHOULI REQUIRED
	modCompileOnly "vazkii.patchouli:Patchouli:$patchouliVersion-FORGE:api"
	modRuntimeOnly "vazkii.patchouli:Patchouli:$patchouliVersion-FORGE"
	// ModKit DEV ONLY
	modImplementation 'com.github.thedarkcolour:ModKit:cc8f1c11ec'
	// FORESTRY REQUIRED
	modImplementation "maven.modrinth:forestry-community-edition:$forestryVersion"

	modImplementation 'maven.modrinth:cofh-core:11.0.2'
	modImplementation 'maven.modrinth:thermal-foundation:11.0.6'
	modImplementation 'maven.modrinth:thermal-dynamics:11.0.1'

	// DEV ONLY
	compileOnly 'org.jetbrains:annotations:23.0.0'
}

// Include resources generated by data generators.
sourceSets.main.resources { srcDir 'src/generated/resources' }

var generateModMetadata = tasks.register('generateModMetadata', ProcessResources) {
	var replaceProperties = [
			'version'              : project.version,
			'forgeVersionRange'    : forgeVersionRange,
			'jeiVersionRange'      : jeiVersionRange,
			'patchouliVersionRange': patchouliVersionRange,
			'fmlVersionRange'      : fmlVersionRange,
			'forestryVersionRange' : forestryVersionRange,
	]
	inputs.properties replaceProperties
	expand replaceProperties

	from 'src/main/templates'
	into 'build/generated/sources/modMetadata'
}
sourceSets.main.resources.srcDir generateModMetadata

idea.project.settings {
	taskTriggers {
		afterSync generateModMetadata
	}
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = 'UTF-8'
}

idea {
	module {
		downloadSources = true
		downloadJavadoc = true
	}
}

if (System.getenv('CURSEFORGE_TOKEN')) {
	curseforge {
		apiKey = System.getenv('CURSEFORGE_TOKEN')

		project {
			id = project.curseforgeId
			changelogType = 'markdown'
			changelog = getChangelog(version)

			releaseType = 'release'

			addGameVersion(project.minecraftVersion)
			addGameVersion('Forge')
			addGameVersion('Java 17')

			mainArtifact(reobfJar.archiveFile) {
				displayName = "Gendustry: Community Edition ${project.version}"
				relations {
					requiredDependency 'forestry-community-edition'
				}
			}
		}
	}
}

modrinth {
	token = System.getenv('MODRINTH_TOKEN')
	projectId = project.modrinthId
	versionName = "Gendustry: Community Edition $version"
	versionNumber = version.toString()
	versionType = 'release'
	gameVersions = [minecraftVersion]
	loaders = ['forge']
	changelog = getChangelog(project.version)

	uploadFile = reobfJar

	dependencies {
		required.project('forestry-community-edition')
	}
}

static def getChangelog(Object version) {
	version = version.toString()

	def file = new File('changelog.md')
	if (!file.exists()) {
		return 'Changelog file not found'
	}

	// Relies on the changelog block being "##blahblahblah_VERSION" where _ is a space
	def content = file.text.normalize().split("##.* ")

	for (final def chunk in content) {
		if (chunk.isEmpty()) continue

		def lineTerminatorIndex = chunk.findIndexOf { c -> c == '\n' || c == '\r' }
		def versionString = chunk.substring(0, lineTerminatorIndex)

		if (versionString == version) {
			return "## Gendustry $version\n" + chunk.substring(lineTerminatorIndex + 1)
		}
	}

	// Fallback in case this fails
	return "Gendustry Update ${version}"
}
