org.gradle.daemon=true
org.gradle.jvmargs=-Xmx3G
org.gradle.caching=true
org.gradle.parallel=true

curseforgeId=1179084
modrinthId=2zkSGMyK

# Gendustry
gendustryVersion=1.0.4

# Minecraft
minecraftVersion=1.20.1
mappingsVersion=2023.06.26
# Forge
forgeVersion=47.4.0
forgeVersionRange=[47.1.0,)
fmlVersionRange=[43,)
# JEI
jeiVersion=15.20.0.106
jeiVersionRange=[15,)
# Patchouli
patchouliVersion=1.20.1-84
patchouliVersionRange=[1.20.1-84,)
# Forestry
forestryVersion=2.10.0
forestryVersionRange=[2.3.0,)
