modLoader="javafml"
loaderVersion="${fmlVersionRange}"
issueTrackerURL="https://github.com/thedarkcolour/Gendustry/issues"

license="GNU GPLv3"

[[mods]]
	modId="gendustry"
	version="${version}"
	displayName="Gendustry"
	credits="bdew for original mod and ideas"
	authors="thedarkcolour"
	description='''
	Machines for manipulation of Forestry genetics.
	'''

[[dependencies.forestry]]
	modId="forge"
	mandatory=true
	versionRange="${forgeVersionRange}"
	ordering="NONE"
	side="BOTH"

[[dependencies.forestry]]
	modId="patchouli"
	mandatory=true
	versionRange="${patchouliVersionRange}"
	ordering="NONE"
	side="BOTH"

[[dependencies.forestry]]
	modId="jei"
	mandatory=true
	versionRange="${forestryVersionRange}"
	ordering="NONE"
	side="CLIENT"

[[dependencies.forestry]]
	modId="jei"
	mandatory=false
	versionRange="${jeiVersionRange}"
	ordering="NONE"
	side="CLIENT"
